### PR TITLE
fix: remove sudo as a requirement for NGINX

### LINKED ISSUE #309: Investigate to avoid sudo access to NGINX test
Investigate if it's possible to run all provider tests from local target folder instead of copying to system folders. This could eliminate need for sudo access. 
Or an option in nextest to accept sudo password.

### PR DESCRIPTION
**Pull request by walterchris**

### CODE REVIEW

File: plugins/ossl_prov/integration-tests/nginx/src/nginx_tests.rs [hunk 1]
```diff
@@ -106,7 +106,7 @@ mod integration {
             }
         }
 
-        stop_nginx();
+        stop_nginx(&keymat_dir);
```
Comment (rajesh-gali) [inline plugins/ossl_prov/integration-tests/nginx/src/nginx_tests.rs]: nginx is stopped only if test is successfull, I think nginx needs to be stopped if it has been started or start_nginx fails?

Comment (rajesh-gali) [reply plugins/ossl_prov/integration-tests/nginx/src/nginx_tests.rs]: we could use drop trait to cleanup nginx ?

**Review by rajesh-gali — DISMISSED** [review]

File: plugins/ossl_prov/integration-tests/nginx/src/nginx_tests.rs [hunk 2]
```diff
@@ -378,91 +386,104 @@ http {{
...
+            let error_log = self.keymat_dir.join("logs").join("error.log");
+            let openssl_conf = self.keymat_dir.join("openssl-provider.cnf");
+            let _ = Command::new("nginx")
+                .args(["-s", "stop"])
+                .arg("-p")
+                .arg(&self.keymat_dir)
+                .arg("-e")
+                .arg(&error_log)
+                .arg("-c")
+                .arg(&nginx_conf)
```
[the remark this answers is not in the document]
Comment (walterchris) [reply plugins/ossl_prov/integration-tests/nginx/src/nginx_tests.rs:410]: Dismissed.

**Review by rajesh-gali — APPROVED** [review]
